### ISSUE TITLE
Getting warning messages in post-step

### ISSUE THREAD

**Issue by h0x0er** [erlef/setup-beam#136]
Hello maintainers.. 
I am having an issue with `setup-beam`. While using it in one of my workflow.. I am getting `warning messages` in `post-step` of one of my `action`, [check](https://github.com/h0x0er/elixir-warning-investigation/runs/7945216817?check_suite_focus=true#step:10:1). The warning message disappears when `disable_problem_matchers` is set to `true`  [check here](https://github.com/h0x0er/elixir-warning-investigation/runs/7944777021?check_suite_focus=true#step:10:1).

Do you guys knows this issue with `disable_problem_matchers` ? if yes, do you know how this can be fixed ?

Thanks :)

**Comment by starbelly** [comment]
It looks like the warning regex for the [mix compiler problem matchers](https://github.com/erlef/setup-beam/blob/4518ce17a4986690fea547eba415876400f36105/.github/elixir-matchers.json#L31) is the culprit here at a first glance. I think this might just be how problem matches work in github actions. That is to say, at a glance it looks like the owner tag for a problem matcher doesn't mean it just gets applied during mix compile, but I'd have to look further to verify that. 

Or someone who knows more about problem matchers and github actions can chime in here.

**Comment by paulo-ferraz-oliveira** [comment]
Hello, @h0x0er.

Thanks for bringing this to our attention.

I was not aware of this problem, with the matchers, but I tend not to use them (not doing a lot of Elixir). Disabling them, via the option you mention, shouldn't be an issue, though, i.e. you'll not have the results they usually return, but you may also not want to use them.

In any case, if you want to dig deeper into this

* ... here's the definition of the matchers, for this action: https://github.com/erlef/setup-beam/blob/main/.github/elixir-matchers.json, and
* ... here's some generic documentation about matchers: https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md

I did find we have some (maybe invalid?) warnings in the action's CI, yesterday, while creating a PR, but since they're not super important, I postponed looking at the actions' matchers 😕 

I can see that result `Mon, 22 Aug 2022 05:29:17 GMT:NewAuditClient created` is getting matched by `^(.*):(\d+):(.*)` (this seems like a very generic reg.exp. in any case), so maybe the fix is somewhere around https://github.com/erlef/setup-beam/blob/main/.github/elixir-matchers.json#L66.

These matchers, of course, rely on output from what the action can "see" and sometimes that output is not standardised enough to have more specific reg.exp. to target them, e.g. if all `dialyzer` output messages started with `[dialyzer]` the reg.exp. could target those results easier, like `^[dialyzer] (.*):(\d+):(.*)`, or similar.

Pull requests are welcome 👍

**Comment by h0x0er** [comment]
@paulo-ferraz-oliveira thanks for the details..

**Comment by paulo-ferraz-oliveira** [comment]
@h0x0er, is this something you want to tweak via a pull request? Or should we close this issue?
