### ISSUE TITLE
Error with rebar in `.tool-versions`

### ISSUE THREAD

**Issue by asmodehn** [erlef/setup-beam#177]
Hello,

With this in my github workflow:
```
[...]
    - uses: erlef/setup-beam@v1
      with:
        version-type: strict
        version-file: .tool-versions
[...]
```

and this in my `.tool-versions`:
```
erlang 25.1.2
elixir 1.13.4-otp-25
direnv 2.28.0
nodejs 18.12.0
rebar 3.15.0
```

The setup-beam action fails like so :
```
Run erlef/setup-beam@v1
Parsing version file at .tool-versions
Installing Erlang/OTP OTP-25.1.2 - built on ubuntu-22.04
Using Elixir v1.13.4 (built for Erlang/OTP 25)
Installing Elixir v1.13.4-otp-25
Running mix local.rebar,--force
Running mix local.hex,--force
Installing rebar3 3.15.0
  /home/runner/work/_actions/erlef/setup-beam/v1/dist/install-rebar3.sh 3.15.0
  Installed rebar3 version follows
  escript: exception error: undefined function rebar3:main/1
    in function  escript:run/2 (escript.erl, line 750)
    in call from escript:start/1 (escript.erl, line 277)
    in call from init:start_em/1 
    in call from init:do_boot/3 
  Error: The process '/home/runner/work/_actions/erlef/setup-beam/v1/dist/install-rebar3.sh' failed with exit code 127
  ```
  
  I removed it to get everything to work as expected, as it is not useful in my usecase, since mix will install it locally.
  But I thought I ll report here anyway, in case it helps to track down the actual issue...
  
 Cheers

**Comment by paulo-ferraz-oliveira** [comment]
> I removed it

What is "it" in this context? The `.tool-versions` line pertaining to `rebar3` (a.k.a. as `rebar` by `asdf`)?

I should add this to the test suite, if it's not already there, to have a starting point for the fix.

Thanks for the report.

**Comment by paulo-ferraz-oliveira** [comment]
I'm gonna start checking this now, but I'd like to know if `rebar3` 3.15.0 runs on OTP 25 with no issue, out-of-the-box.

**Comment by paulo-ferraz-oliveira** [comment]
As per the linked pull request (just above), and my test results, I conclude that `rebar3` 3.15.0 is just not compatible with OTP 25, as can be seen in [the result we obtain](https://github.com/erlef/setup-beam/actions/runs/3934035332/jobs/6728365178#step:6:49) when bumping the test to use 3.16.0. I'll still leave the test there, since I feel it's important, but I'm closing this issue. Feel free to re-open after you test, locally, that `rebar3` 3.15.0 doesn't react the same in the folder where you have it be managed by `asdf` alongside Erlang/OTP 25.1.2.
