### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by devblueray** [erlef/setup-beam#186]
A couple days ago, started getting this error:

:dialyzer.run error: File not found: /runner/_work/_temp/.setup-beam/otp/lib/dialyzer-5.0.4/ebin/erl_bif_types.beam when running mix dialyzer

Thoughts?

**Comment by starbelly** [comment]
This is odd. Dialyzer will look for that file among others when trying to compute the md5 implementation in order to persist the built PLT to disk. The error your encountering seems to suggest that the file was not in the artifact that unpacked (i.e., otp) or was somehow removed. 

Can you provide us with details on how we can reproduce this? A sample workflow would be best.

**Comment by devblueray** [comment]
Hi Bryan,

Thank you for the reply.  I figured out the issue.  My PLT cache appears to
have become corrupted in some way.  Once I removed that cache and let it
regenerate, everything started working again.

**Comment by starbelly** [comment]
@devblueray I'm glad you found your way out! Thanks for opening the issue :)
