### ISSUE TITLE
Dynamically discover include path on Windows

### ISSUE THREAD

**Issue by samaaron** [erlef/setup-beam#89]
I'm using this action to build a NIF.

On Linux, the appropriate headers are automatically available to cmake. However, on Windows this isn't the case and a path has to be supplied manually to add to the include paths. Could this be exposed as some sort of variable to be referenced and passed into cmake?

The alternatives appear to be to either hard code the include path (but that's brittle and will break when a new version is released) or to include the header files locally (which also is brittle, but likely to be slower to break).

**Comment by paulo-ferraz-oliveira** [comment]
Hi, Sam. (we met a while ago, in Stockholm :-), you presented stuff on Sonic Pi, with Joe)

I'm not sure I understand your request, sorry.

The action uses prebuilt Windows images (it doesn't build them locally). Where would we use the "variable to be referenced and passed into cmake"?

Could you please elaborate further? I fail to understand what's breaking. Should it work in a version of Windows it doesn't? Could you point me to a repo. or an example where I see it fail so I understand better?

Thanks.

**Comment by samaaron** [comment]
Hey Paulo,

super cool we already met - hi again!

Just to be clear - sorry I wasn't clearer earlier - nothing is broken. The only issue I've got is that when I'm building a NIF, I need to tell cmake where to find the .h files such as `erl_nif.h`. On Linux, this seems to be handled automatically as these must be placed in a standard place and this is the kind of thing Linux is good at. However, in Windows world things aren't quite as simple.

 For my use case it's not just good enough that erl and friends are available on the system PATH. What I'm really looking for is a way of knowing *where* the BEAM is installed on the file system so I can point cmake to the right place to find the header files.

I'm definitely no expert in GitHub Actions but I think there's some sort of variable system that can be used to communicate across actions. For example, something like this might work: https://www.edwardthomson.com/blog/github_actions_15_sharing_data_between_steps.html

In order to fix this issue I'm currently just including the header files in my project tree which works, but isn't ideal - it would be much nicer to be able to point to the ones specific to the version of  the BEAM being used for the build.

Hope this makes sense.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for the detail. I think I understand your problem better now (hopefully 😄).

If you look at https://github.com/erlef/setup-beam/blob/main/src/setup-beam.js you'll see where we're setting outputs (look for `setOutput`).

What I believe you're proposing is an output that specifies where the BEAM is actually installed, for Windows systems. Not sure if it can be done, since I've never done it 😄.

This is how I added Windows to the action:
1. I have a computer running Windows (I don't actually use it for development),
2. I learned PowerShell (the basics),
3. I "ported" the Linux installer (.sh - https://github.com/erlef/setup-beam/blob/main/src/install-otp.sh) to "Windows format" (https://github.com/erlef/setup-beam/blob/main/src/install-otp.ps1)
4. https://github.com/erlef/setup-beam/blob/main/src/install-otp.ps1#L16 is how I obtained the install path

Let me know if this is helpful. Can you give me an example of a simple flow where you'd get a file name you're looking for so I can try to create an example repo. to replicate?

Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
I created an example repo for this. Let me know if this is helpful https://github.com/paulo-ferraz-oliveira/setup_beam_example/runs/5149669088?check_suite_focus=true#step:4:11, ie. if what you want is one of those lib.s in some kind of shared variable (?).

**Comment by paulo-ferraz-oliveira** [comment]
In this other example, I:
* set an env. variable with the path to `lib`: https://github.com/paulo-ferraz-oliveira/setup_beam_example/runs/5150119445?check_suite_focus=true#step:4:4
* use it, in a later step, to list that path's contents: https://github.com/paulo-ferraz-oliveira/setup_beam_example/runs/5150119445?check_suite_focus=true#step:5:11

**Comment by paulo-ferraz-oliveira** [comment]
@samaaron, just checking in. Did any of the previous suit you? Do you have further suggestions on how to improve this?
Thanks.

**Comment by samaaron** [comment]
Hey @paulo-ferraz-oliveira - apologies I got sidetracked making a new Sonic Pi Beta (I ended up just including the Erlang NIF header files in the tree) and now it's school holiday and we're currently looking after our 3 kids and 2 others - it's a bit hectic!

This definitely looks very useful - it's certainly some fancy powershell magic! It seems a little odd that you have to search for the install path when this is something the action is doing - perhaps the action doesn't know where it will end up?

I guess with respect to further suggestions, it would be nice if there was a built-in option to the action that automatically set an env variable with the location of the root directory of the BEAM installation with which you could then relatively append a partial path to the internal directory of interest (in our case it's the header files necessary to compile a NIF).

Thanks so much for your kind and generous efforts highlighting how to make this possible :-)

**Comment by paulo-ferraz-oliveira** [comment]
> perhaps the action doesn't know where it will end up?

Exactly. The action runs the installer provided by the OTP team. We take a binary and install it. I'm not sure there's parameters to be passed, in order to make it more deterministic, but I haven't explored it further.

> the location of the root directory of the BEAM installation with which you could then relatively append a partial path to the internal directory of interest 

You mean `lib` directly? Its parent? Another dir? I guess setting some env. variables shouldn't be too much of a bother, though I'd prefer to do it for all the environments (ie. Ubuntu also), with the same name and accessible in the same way (which is what we aimed to do with Windows in the first place, coming from Ubuntu). And then document this, of course.

**Comment by paulo-ferraz-oliveira** [comment]
Here's a new example, that'll hopefully fulfil your expectations: https://github.com/paulo-ferraz-oliveira/setup-beam-example/blob/main/.github/workflows/ci.yml#L13

This produces: https://github.com/paulo-ferraz-oliveira/setup-beam-example/runs/5225769453?check_suite_focus=true#step:4:8

In summary:

`${{env.INSTALL_DIR_FOR_OTP}}` outputs (e.g.) `C:\Program Files\erl-24.2.1`

**Note**: if the repo.s branch gets accepted as a pull request, and merged, some more env. variables will also be available, for consistency, namely https://github.com/paulo-ferraz-oliveira/setup-beam/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R193

**Comment by paulo-ferraz-oliveira** [comment]
Environment variables are now available in v1.11.0. Check the README for more information.

**Comment by samaaron** [comment]
Awesome - thank-you so much!
